name: hero action

on:
  push:
    branches: main

jobs:
  name: hero job
  runs-on: ubuntu-latest

  actions:
    - name: checkout
      uses: actions/checkout@v2

    - name: log
      script: /
        ls
        echo ${{ github }}
