name: hero action

on:
  push:
    branches: master
  workflow_dispatch:

jobs:
  hero-job:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: log
        run: |
          ls
          echo ${{ github.event_name }} ${{ github.ref }}  ${{ github.repository }} ${{ github.workspace }} ${{ job.status }} ${{ runner.os }} ${{ runner.name }}
