name: hero action

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  hero-job:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: log
        run: |
          ls
          echo ${{ github }}
